// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP7sctHmsS3KdzLmQ5-vHDTNAV8LccX2c',
    appId: '1:300536682296:web:2cb2d78e1ed014197a93cd',
    messagingSenderId: '300536682296',
    projectId: 'dream-burger-sample-work',
    authDomain: 'dream-burger-sample-work.firebaseapp.com',
    storageBucket: 'dream-burger-sample-work.appspot.com',
    measurementId: 'G-LDFYV0VQZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJgPTODe81yqAShWNbpbglaABG3Ik8SYM',
    appId: '1:300536682296:android:0ef98085473df3c07a93cd',
    messagingSenderId: '300536682296',
    projectId: 'dream-burger-sample-work',
    storageBucket: 'dream-burger-sample-work.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjyO9VOJ06jOfheynUCkrNzdpwFrkz3C0',
    appId: '1:300536682296:ios:a8df7cbd3acdc7a17a93cd',
    messagingSenderId: '300536682296',
    projectId: 'dream-burger-sample-work',
    storageBucket: 'dream-burger-sample-work.appspot.com',
    iosBundleId: 'com.example.dreamBurgerSampleWork',
  );

}